first_sting = input('Введите первую строку:\n')
second_sting = input('Введите вторую строку:\n')
third_sting = input('Введите третью строку:\n')
fourth_sting = input('Введите четвертую строку:\n')
file = open('Homework 9\\task_2_file.txt','w')
file.write(first_sting + '\n')
file.write(second_sting + '\n')
file.close()
file = open('Homework 9\\task_2_file.txt','a')
file.write(third_sting + '\n')
file.write(fourth_sting + '\n')
file.close()