# Generated by Django 5.0.1 on 2024-02-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_of_country', models.CharField(choices=[('Белорусская кухня', 'Белорусская кухня'), ('Русская кухня', 'Русская кухня'), ('Американская кухня', 'Американская кухня'), ('Азиатская кухня', 'Азиатская кухня'), ('Армянская кухня', 'Армянская кухня'), ('Греческая кухня', 'Греческая кухня'), ('Грузинская кухня', 'Грузинская кухня'), ('Европейская кухня', 'Европейская кухня'), ('Индийская кухня', 'Индийская кухня'), ('Итальянская кухня', 'Итальянская кухня'), ('Кавказская кухня', 'Кавказская кухня'), ('Мексиканская кухня', 'Мексиканская кухня'), ('Немецкая кухня', 'Немецкая кухня'), ('Турецкая кухня', 'Турецкая кухня'), ('Тайская кухня', 'Тайская кухня'), ('Средиземноморская кухня', 'Средиземноморская кухня'), ('Узбекская кухня', 'Узбекская кухня'), ('Украинская кухня', 'Украинская кухня'), ('Французская кухня', 'Французская кухня'), ('Японская кухня', 'Японская кухня')], max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Shefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about_me', models.CharField(max_length=700)),
                ('cuisines_country', models.ManyToManyField(to='dishes.cuisines')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_description', models.TextField()),
                ('dish_prise', models.IntegerField()),
                ('dish_weight', models.IntegerField()),
                ('dish_photo', models.ImageField(upload_to='')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='dishes.shefs')),
            ],
        ),
    ]
