# Generated by Django 5.0.1 on 2024-02-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_remove_dishes_dish_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='dish_photo',
            field=models.ImageField(default=1, upload_to='dishes/images/dishes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shefs',
            name='photo',
            field=models.ImageField(default=1, upload_to='dishes/images/shefs/'),
            preserve_default=False,
        ),
    ]
