# Generated by Django 5.0.1 on 2024-02-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_shefs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shefs',
            name='user',
        ),
    ]
