# Generated by Django 5.0.1 on 2024-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_remove_shefs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_photo',
            field=models.ImageField(upload_to='static/images/dishes/'),
        ),
        migrations.AlterField(
            model_name='shefs',
            name='photo',
            field=models.ImageField(upload_to='static/images/shefs/'),
        ),
    ]
