# Generated by Django 5.0.1 on 2024-02-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_alter_dishes_dish_photo_alter_shefs_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisines',
            name='cuisine_of_country',
            field=models.CharField(max_length=35),
        ),
    ]
