# Generated by Django 5.0.1 on 2024-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_alter_cuisines_cuisine_of_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shefs',
            name='about_me',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='shefs',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/shefs/'),
        ),
    ]
